"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var publisher_1 = require("./publisher");
var subscriber_1 = require("./subscriber");
var gp = new publisher_1.NewsPaper();
new subscriber_1.Reader('fardin_id', gp);
new subscriber_1.Reader('zohra_id', gp);
new subscriber_1.Reader('hayah_id', gp);
gp.publish('Breaking News! Julen ar har och fortfarande ingen sno! det ar en stor kris');
console.log(' ************ Weather Station ************ ');
var weatherStation = new publisher_1.WeatherStation(22, 20, 30);
new subscriber_1.UserInterface(weatherStation);
new subscriber_1.Logger(weatherStation);
new subscriber_1.AlertSystem(weatherStation);
weatherStation.setTemperature(48);
